# Daily Data Science 003

Will be learning the Pandas Library.

# Pandas

## Loading the Libraries and Datasets

In [20]:
!pip install pandas

Requirement already satisfied: pandas in /home/pranshu/miniconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /home/pranshu/miniconda3/lib/python3.13/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/pranshu/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/pranshu/miniconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/pranshu/miniconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /home/pranshu/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [21]:
!ls Datasets/datasets-session-16

bollywood.csv  bollywood.xlsx  kohli_ipl.csv  subs.csv	subs.xlsx

## What is Pandas?

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of Python programming language.

## Pandas Series

A pandas series is like a column in a table. It is a 1D array holding data of any type.

## Importing Pandas

In [22]:
import pandas as pd
import numpy as np # Recommended for numerical operations

## Series from Lists

In [23]:
# string
country = ['India', 'USA', 'UK', 'Germany', 'France']

# To convert the list to pandas series
print(pd.Series(country)) # here the string is referred as object in pandas.
print()

# integer
batsman = [10, 4, 2, 6, 1]
print(pd.Series(batsman)) # here the integer is referred as int64 in pandas.

0      India
1        USA
2         UK
3    Germany
4     France
dtype: object

0    10
1     4
2     2
3     6
4     1
dtype: int64

In [24]:
#  To give custom index to the series, using the index parameter
print(pd.Series(country, index=['a', 'b', 'c', 'd', 'e'])) # here the string is referred as object in pandas.
print()
print(pd.Series(batsman, index=['a', 'b', 'c', 'd', 'e'])) # here the integer is referred as int64 in pandas.
print()

a      India
b        USA
c         UK
d    Germany
e     France
dtype: object

a    10
b     4
c     2
d     6
e     1
dtype: int64

In [25]:
# To give a name to the series, using the name parameter
print(pd.Series(country, index=['a', 'b', 'c', 'd', 'e'], name='Countries')) # here the string is referred as object in pandas.
print()
print(pd.Series(batsman, index=['a', 'b', 'c', 'd', 'e'], name='Runs')) # here the integer is referred as int64 in pandas.

a      India
b        USA
c         UK
d    Germany
e     France
Name: Countries, dtype: object

a    10
b     4
c     2
d     6
e     1
Name: Runs, dtype: int64

In [26]:
# Using Dictionary to create a series
country_dict = {'a': 'India', 'b': 'USA', 'c': 'UK', 'd': 'Germany', 'e': 'France'}
print(pd.Series(country_dict, name='Countries')) # here the string is referred as object in pandas.
print()
batsman_dict = {'a': 10, 'b': 4, 'c': 2, 'd': 6}
print(pd.Series(batsman_dict, name='Runs')) # here the integer is referred as int64 in pandas.

# The Key in the dictionary becomes the index of the series and the value becomes the data of the series.

a      India
b        USA
c         UK
d    Germany
e     France
Name: Countries, dtype: object

a    10
b     4
c     2
d     6
Name: Runs, dtype: int64

## Series Attribute

In [27]:
# size attribute
print(pd.Series(country).size) # size of the series
print(pd.Series(batsman_dict).size)

5
4

In [28]:
# dtype attribute
print(pd.Series(country).dtype) # dtype of the series
print(pd.Series(batsman_dict).dtype) # dtype of the series

object
int64

In [29]:
# name attribute
print(pd.Series(country).name) # name of the series
print(pd.Series(batsman_dict, name='Runs').name) # name of the series

None
Runs

In [30]:
# isunique attribute
print(pd.Series(country).is_unique) # check if the values in the series are unique or
print(pd.Series(batsman_dict).is_unique) # check if the values in the series are unique or not

True
True

In [31]:
# index attribute in pandas
print(pd.Series(country).index) # index of the series
print(pd.Series(batsman_dict).index) # index of the series

RangeIndex(start=0, stop=5, step=1)
Index(['a', 'b', 'c', 'd'], dtype='object')

In [32]:
# values attribute in pandas
print(pd.Series(country).values) # values of the series
print(pd.Series(batsman_dict).values) # values of the series
print(type(pd.Series(country).values)) # type of the values of the series

['India' 'USA' 'UK' 'Germany' 'France']
[10  4  2  6]
<class 'numpy.ndarray'>

## Series using the read_csv() Function

In [ ]:
# here we will be using this dataset
# /home/pranshu/Documents/Daily-Data-Science/Datasets/datasets-session-16/bollywood.csv

 # Series using the read_csv function
bollywood = pd.read_csv('/home/pranshu/Documents/Daily-Data-Science/Datasets/datasets-session-16/bollywood.csv')
kohli = pd.read_csv('/home/pranshu/Documents/Daily-Data-Science/Datasets/datasets-session-16/kohli_ipl.csv')
subs = pd.read_csv('/home/pranshu/Documents/Daily-Data-Science/Datasets/datasets-session-16/subs.csv')

In [45]:
bollywood.describe() # to get the summary of the dataset

                          movie          lead
count                      1500          1500
unique                     1497           566
top     Tanu Weds Manu: Returns  Akshay Kumar
freq                          2            48

In [46]:
kohli.describe() # to get the summary of the dataset

         match_no        runs
count  215.000000  215.000000
mean   108.000000   30.855814
std     62.209324   26.229801
min      1.000000    0.000000
25%     54.500000    9.000000
50%    108.000000   24.000000
75%    161.500000   48.000000
max    215.000000  113.000000

In [49]:
subs_series = pd.read_csv('/home/pranshu/Documents/Daily-Data-Science/Datasets/datasets-session-16/subs.csv').squeeze() # to read the csv file and convert it to series
subs_series

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64